sudo: false
language: java
jdk:
  - oraclejdk8

script: "./travis.sh"
cache:
  directories:
    - .cache
before_script:
 - chmod +x travis.sh
 - mkdir lib

env:
  - PHPSTORM_ENV=2017.2.3
  - PHPSTORM_ENV=eap

matrix:
  allow_failures:
    - env: PHPSTORM_ENV=eap
